# bootstrap file to provide the program with necessary information
# this file is developers only

BASIC_TYPES:
  integer: "^[+-]?[0-9]+$|^[ ]*$"
  real: "^[+-]?(([0-9]+([.][0-9]*)?|[.][0-9]+))([Ee][+-]?[0-9]+)?$|^$"
  boolean: "^(0|1|true|false|yes|no)$"
  date: "(^[0-9]{4}-[0-1][0-9]-[0-3][0-9])$|^([0-9]{4}[0-1][0-9][0-3][0-9])$|^$"
  timestamp: "(^[0-9]{4}-[0-1][0-9]-[0-3][0-9])|^([0-9]{4}[0-1][0-9][0-3][0-9])( [0-2][0-9]:[0-6][0-9]:[0-6][0-9]){0,1}$|^$"
  text: "<nope>"

SUB_TYPES:
  integer: [integer, bigint]
  real: [real, double precision, numeric, decimal]
  boolean: [boolean, bool]
  date: [date]
  timestamp: [timestamp]
  text: [text, serial, bigserial]

# Subdirs within the working directory.
WORKDIR_STRUCTURE: docs,sql,schemas,todo,done,tmp,tests

# versions
DIDO_VERSION_MAJOR: 0
DIDO_VERSION_MINOR: 7
DIDO_VERSION_PATCH: 5

SERVERS:
  datawarehouse_dev: 10.10.12.12
  datawarehouse_acc: 10.10.12.13
  datawarehouse_prd: 10.10.12.6

BEGINNING_OF_WORLD: 1970-01-01 00:00:00
END_OF_WORLD: 9999-12-31 23:59:59
