# bootstrap file to provide the program with necessary information
# this file is developers only

BASIC_TYPES:
  integer: "^[+-]?[0-9]*$"
  real: "^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$"
  boolean: "^(0|1|true|false)$"
  date: "(^[0-9]{4}-[0-1][0-9]-[0-3][0-9])$|^([0-9]{4}[0-1][0-9][0-3][0-9])$|^$"
  timestamp: "(^[0-9]{4}-[0-1][0-9]-[0-3][0-9])|^([0-9]{4}[0-1][0-9][0-3][0-9])( [0-2][0-9]:[0-6][0-9]:[0-6][0-9]){0,1}$|^$"
  text: "<nope>"

SUB_TYPES:
  integer: [integer, bigint]
  real: [real, double precision, numeric, decimal]
  boolean: [boolean, bool]
  date: [date]
  timestamp: [timestamp]
  text: [text, serial, bigserial]

# Subdirs within the working directory.
WORKDIR_STRUCTURE: docs,sql,schemas,todo,done,tmp,tests

# versions
ODL_VERSION: 0.9.1
DIDO_VERSION: 0.7.3

SERVERS:
  DEVELOPMENT: 10.10.12.12
  PRODUCTION: 10.10.12.6

BEGINNING_OF_WORLD: 1970-01-01 00:00:00
END_OF_WORLD: 9999-12-31 23:59:59
