# bootstrap file to provide the program with necessary information
# this file is developers only

BASIC_TYPES:
  integer: "^[+-]?[0-9]+$|^[ ]*$"
  real: "^[+-]?(([0-9]+([.][0-9]*)?|[.][0-9]+))([Ee][+-]?[0-9]+)?$|^$"
  boolean: "^(0|1|true|false|yes|no)$"
  date: "(^[0-9]{4}-[0-1][0-9]-[0-3][0-9])$|^([0-9]{4}[0-1][0-9][0-3][0-9])$|^$"
  timestamp: "(^[0-9]{4}-[0-1][0-9]-[0-3][0-9])|^([0-9]{4}[0-1][0-9][0-3][0-9])( [0-2][0-9]:[0-6][0-9]:[0-6][0-9]){0,1}$|^$"
  text: "<nope>"

SUB_TYPES:
  integer: [integer, bigint]
  real: [real, double precision, numeric, decimal]
  boolean: [boolean, bool]
  date: [date]
  timestamp: [timestamp]
  text: [text, serial, bigserial]

# Subdirs within the working directory.
WORKDIR_STRUCTURE: docs,sql,schemas,todo,done,tmp,tests

# versions
DIDO_VERSION: 0.8.1
DIDO_VERSION_DATE: 2024-06-20 08:59:00

SERVERS:
  datawarehouse_dev: 10.10.12.12
  datawarehouse_acc: 10.10.12.13
  datawarehouse_prd: 10.10.12.6

BEGINNING_OF_WORLD: 1970-01-01 00:00:00
END_OF_WORLD: 9999-12-31 23:59:59

###########################################
# !!! DON'T CHANGE STUF BELOW THIS LINE !!!
# tables to be created
TABLES:
  schema:
    table_root: attribuutmeta
    template: yes
    comment: <odl>
    schema: <self>
    create_description: yes
    create_data: yes
    table: yes
    data: no

  meta:
    table_root: bestandmeta
    template: meta
    comment: <odl>
    schema: <odl>
    create_description: yes
    create_data: yes
    table: yes
    data: no

  datakwaliteit:
    table_root: datakwaliteit
    template: no
    comment: <odl>
    schema: <odl>
    create_description: yes
    create_data: yes
    table: yes
    data: no

  levering:
    table_root: levering
    template: no
    comment: <odl>
    schema: <odl>
    create_description: yes
    create_data: yes
    table: yes
    data: no

