SUPPLIERS:
  pdirekt:
    data_dictionary:
      schema_source: <P-Direkt>
      column_name: Omschrijving
      data_dict: Data-Dictionary-Gegevenslevering-DGDOO-ZBIOSAL01-Salaris
      # merge_with: Data_Dictionary_pdirekt_addendum.csv

      columns:
        kolomnaam: Veldnaam
        leverancier_kolomnaam: Veldnaam
        leverancier_kolomtype: TYPE
        leverancier_info_1: Omschrijving
        gebruiker_info_1: ATTRIBUTEN
        gebruiker_info_2: TEKSTEN
        gebruiker_info_3: HIERARCHIE
        beschrijving: "Unnamed: 8"


    schema_file: Bronanalyse_Salaris

    origin:
      input: <file>
      source: P-Direkt

# select server to use as POSTGRES_HOST
HOST: development

PROJECT_NAME: salaris
ROOT_DIR: root
WORK_DIR: work

# Allows conversion from leverancier_kolomtype to datatype when datatype is empty
DATATYPES:
    CHAR: text
    CUKY: text
    UNIT: text
    NUMC: integer
    INT4: integer
    DATS: date
    QUAN: numeric
    DEC:  numeric
    CURR: numeric

# columns to show in documentation
# COLUMNS:  [] # Empty list = show all columns

# which columns to write for markdown tables and in which order
COLUMNS:
  - kolomnaam
  - leverancier_info_1
  - datatype
  - beschrijving
  - leverancier_kolomnaam
  - leverancier_kolomtype
  - code_attribuut_sleutel
  - leverancier_info_2
  - code_attribuut
  - code_bronbestand
  - constraints
  - domein
  - verstek
  - positie
  - avg_classificatie
  - veiligheid_classificatie
  - gebruiker_info_1
  - gebruiker_info_2
  - gebruiker_info_3
  - kolom_expiratie_datum
  - attribuut_datum_begin
  - attribuut_datum_einde

# database credentials for ODL database. Do not fill out POSTGRES_USER and _PW
# Will be added by those of your .env file
SERVER_CONFIGS:
  ODL_SERVER_CONFIG:
    POSTGRES_PORT: 5432
    POSTGRES_DB: techniek
    POSTGRES_SCHEMA: datamanagement

  # database credentials for storing the data. _USER and _PW will be added from .env
  DATA_SERVER_CONFIG:
    POSTGRES_PORT: 5432
    POSTGRES_DB: data
    POSTGRES_SCHEMA: odl

  # database credentials for xtracting the data. _USER and _PW will be added from .env
  FOREIGN_SERVER_CONFIG:
    POSTGRES_PORT: 5432
    POSTGRES_DB: data
    POSTGRES_SCHEMA: odl

### Parameters for dido-data-prep

# Indicate whether supplu contains header row or not
HEADERS:
  pdirekt: no

# Rename data on column base
# Conversies voor ikb_jopi: ontbrekende datums worden aangegeven door 0(0000000)
# In DWH is de conventie 29991231
# Niet nodig voor vertaaltabel
RENAME_DATA:
  pdirekt:
    geldig_van:   {"00000000":"99991231", "0": "99991231"}
    geldig_tot:   {"00000000":"99991231", "0": "99991231"}
    gewijzigd_op: {"00000000":"99991231", "0": "99991231"}
    pds_datum_ambtsjubileum: {"re": True, "^$": "99991231"}
    datum_uit_dienst:        {"re": True, "^$": "99991231"}
    bedrag:                  {"re": True, "(.*)-": "-\\1"}

# Definieer de kolommen waarvan de de spaties links en rechts moeten worden gestript
# voor iedere cel. Geef kolommen op als lijst:
#  - [] lege lijst: niets wordt gestript
#  - ['*']: alle kolommen worden gestript
#  - ['a', 'b', 'd']: kolommen a, b, d worden gestript
STRIP_SPACE:
  pdirekt: ['*']

### Parameters for dido-import
# LIMITATIONS faciliteert het instellen van limieten zodat getest kan worden op
# een beperkte hoeveelheid data of dat afgebroken wordt als er teveel fouten zijn gedetekteerd
LIMITATIONS:
  max_rows: 1_000 # <1 = read all rows
  max_errors: 1_000

SNAPSHOTS:
  zip: yes
  destroy_todo: yes

# tables to be created
TABLES:
  schema:
    table_root: attribuut_meta
    template: yes
    comment: <odl>
    schema: <self>
    create_description: yes
    create_data: yes
    table: yes
    data: no
    prefix: ''
    suffix: ''

  meta:
    table_root: bestand_meta
    template: meta
    comment: <odl>
    schema: <odl>
    create_description: yes
    create_data: yes
    table: yes
    data: no
    prefix: 'tabel_uitleg.md'
    suffix: 'einde-meta-info.md'

  datakwaliteit_feit:
    table_root: datakwaliteit_feit
    template: no
    comment: <odl>
    schema: <odl>
    create_description: yes
    create_data: yes
    table: yes
    data: no
    prefix: ''
    suffix: ''

  levering_feit:
    table_root: levering_feit
    template: no
    comment: <odl>
    schema: <odl>
    create_description: yes
    create_data: yes
    table: yes
    data: no
    prefix: ''
    suffix: ''
